routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


	// UserManagement Routes
	// ======== Athuntication ========== //
	// UserManagement Module Require To Access this group Routes
	Route::group([ 'namespace' => 'UserManagement', 'prefix' => 'UserManagement'], function () {

	    Route::get('/', 'UserManagementController@index')->name('usermanagement.index');
		// User CRUD Routes
		Route::resource('users', 'UserController');
        Route::get('change-password','UserController@ChangePassword')->name('password.change');
        Route::post('change-password','UserController@UpdatePassword')->name('password.update');
        Route::put('users/status/{id}', 'UserController@toggleStatus')->name('users.toggleStatus');


        // // User Groups CRUD Routes
        Route::resource('usergroups', 'UserGroupController');
        Route::put('usergroups/status/{id}', 'UserGroupController@toggleStatus')->name('usergroups.toggleStatus');
        // Route::resource('groups', 'UserGroupController')->middleware('module:UserManagement');



	});


Route::resource('products', 'ProductManagement\ProductController');
Route::resource('clients', 'ClientManagement\ClientController');
Route::resource('inventorys', 'InventoryManagement\InventoryController');
Route::resource('carts', 'CartManagement\CartController');
Route::get('/Cart/{id}', 'CartManagement\CartController@add_to_cart')->name('carts.add_to_cart');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    //
}

app/Http/Controllers/ClientManagement/ClientController.php
<?php

namespace App\Http\Controllers\ClientManagement;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Client;
use Carbon\Carbon;
use Illuminate\Support\Str;
use Toastr;
use Auth;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('client.index')->with('clients',Client::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clients = new Client();
        return view('client.create')->with('client',$clients);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
   public function store(Request $request)
    {
         $this->validate($request,[
            "name" => "string|required",
            "address" => "string|required",
            'email' => 'email|required||unique:clients',
            "phone_no" => 'required|max:12|string'
            


        ]);

        $client = new Client;
        $client->name = $request->name;
        $client->address = $request->address;
        $client->email = $request->email;
        $client->phone_no = $request->phone_no;
        $client->slug = Str::slug($request->name,'-');
        $client->user_id = Auth::id();




        $client->save();
        Toastr::success('Client added Successfully', 'Success', ["positionClass" => "toast-bottom-right"]);

        return redirect()->route('clients.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function show($slug){

        $client = Client::where('slug', $slug)->firstorFail();
        return view("client.show", compact('client'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($slug)
    {
        $client =  Client::where('slug',$slug)->firstOrFail();
        return view('client.create')->with('client',$client);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $slug)
    {
         $this->validate($request,[
            "name" => "string|required",
            "address" => "string|required",
            'email' => 'email|required||unique:clients',
            "phone_no" => 'required|max:12|string|nullable'
            


        ]);
        $client = Client::where('slug',$slug)->firstOrFail();

        $client->name = $request->name;
        $client->address = $request->address;
        $client->email = $request->email;
        $client->phone_no = $request->phone_no;
        
        $client->slug = Str::slug($request->name,'-');
        $client->user_id = Auth::id();

         $client->save();
        Toastr::success('Client updated Successfully', 'Success', ["positionClass" => "toast-bottom-right"]);

        return redirect()->route('clients.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/client/partials/form.blade.php
@extends('layouts.block')

@section('b-title')
    <h2> <i class="fa fa-client-hunt"></i> <strong> Add Client  </strong> </h2>
@endsection


@section('b-content')
    <form method="POST" class="form-horizontal form-bordered" action="{{ ($client->slug) ? route('clients.update', $client->slug ) : route('clients.store') }}" autocomplete="off">
        
       
        @csrf
        @if($client->slug)
            @method('PUT')
        @else
            @method('POST')
        @endif

        <div class="form-group @error('name') has-error @enderror @if(session('danger')) has-error @endif">
            <label class="col-md-3 control-label" for="name">Name <span class="text-danger">*</span></label>
            <div class="col-md-9">
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', $client->name) }}"placeholder=" client Name" required autofocus>
                @error('name')
                <span class="help-block animation-slideDown text-danger">{{ $message }}</span>
                @enderror
                @if(session('danger'))
                    <span class="help-block animation-slideDown text-danger">{{session('danger')}}</span>
                @endif
            </div>
        </div>
        <div class="form-group @error('address') has-error @enderror">
            <label class="col-md-3 control-label" for="address">Address<span class="text-danger">*</span></label>
            <div class="col-md-9">
                <input type="text" id="address" name="address" class="form-control" value="{{ old('address', $client->address) }}"       placeholder="Client Address" required >
                @error('address')
                <span class="help-block animation-slideDown text-danger">{{ $message }}</span>
                @enderror
            </div>
        </div>
        <div class="form-group @error('email') has-error @enderror">
            <label class="col-md-3 control-label" for="email">Email<span class="text-danger">*</span></label>
            <div class="col-md-9">
                <input type="text" id="email" name="email" class="form-control" value="{{ old('email', $client->email) }}"placeholder="Client Email" required >
                @error('email')
                <span class="help-block animation-slideDown text-danger">{{ $message }}</span>
                @enderror
            </div>
        </div>
        <div class="form-group @error('phone_no') has-error @enderror">
            <label class="col-md-3 control-label" for="phone_no">Phone No<span class="text-danger">*</span></label>
            <div class="col-md-9">
                <input type="number" id="phone_no" name="phone_no" class="form-control" value="{{ old('phone_no', $client->phone_no) }}"       placeholder="Client Phone No" required >
                @error('phone_no')
                <span class="help-block animation-slideDown text-danger">{{ $message }}</span>
                @enderror
            </div>
        </div>
        <div class="form-group form-actions">
            <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-paper-plane"></i> Submit</button>
                <button type="reset" class="btn btn-sm btn-warning"><i class="fa fa-repeat"></i> Reset</button>
            </div>
        </div>
    </form>
@endsection

resources/views/client/partials/info.blade.php
@extends('layouts.block', ["b_options" => 'ft'])

@section('b-title')
   <h2> <i class="fa fa-file-o"></i> <strong>{{ $client->name }}</strong> Info</h2>
@overwrite

@section('b-content')
    @parent
    <table class="table table-borderless table-striped">
        <tbody>
        <tr>
            <td style="width: 20%;"><strong>Email</strong></td>
            <td>{{ $client->email  }}</td>
        </tr>
        <tr>
            <td><strong>Address</strong></td>
            <td> {{ $client->address}} </td>
        </tr>
        <tr>
            <td><strong>Contact</strong></td>
            <td> {{ $client->phone_no ?? "Null" }} </td>
        </tr>
        
        <tr>
            <td><strong>Registered Date</strong></td>
            <td> {{ $client->created_at  }} </td>
        </tr>
        <tr>
            <td><strong>Last Update</strong></td>
            <td> {{ $client->updated_at  }} </td>
        </tr>
        
        </tbody>
    </table>

@overwrite

resources/views/client/partials/list.blade.php
@extends('layouts.block' , [ 'b_type' => 'table', "b_options" => 'ft'])

@section('b-title')
    <h2> <i class="fa fa-users"></i> <strong> Clients </strong></h2>
@overwrite
@section('b-subtitle')
    List
@overwrite

@section('b-options')
    <a href="{{ route('clients.create') }}" class="btn btn-alt btn-sm btn-default" data-toggle="tooltip" title="" data-original-title="Create Product"><i class="fa fa-plus"></i></a>
@overwrite

@section('b-thead')
    <tr>
        <th class="text-center">ID</th>
        <th>Name</th>
        <th>Address</th>
        <th class="text-center">Email</th>
        <th class="text-center">Phone Number</th>
        <th class="text-center">Actions</th>
    </tr>
@endsection

@section('b-tbody')
    @foreach ($clients as $row)
        <tr>
            <td class="text-center">
                {{ $row->id }}
            </td>
            <td class="text-center">
                {{ $row->name }}
            </td >
            <td class="text-center">
                {{ $row->address }}
            </td>
            <td class="text-center">
                {{ $row->email }}
            </td>
            <td class="text-center">
                {{ $row->phone_no }}
            </td>
            
            <td class="text-center">
                <div class="btn-group">
                    <a href="{{ route('clients.show', $row->slug) }}" data-toggle="tooltip" title="View" class="btn btn-xs btn-info"><i class="fa fa-eye"></i></a>
                    <a href="{{ route('clients.edit',$row->slug) }}" data-toggle="tooltip" title="Edit" class="btn btn-xs btn-primary"><i class="fa fa-pencil"></i></a>

                </div>
            </td>
        </tr>
    @endforeach

@endsection

resources/views/client/partials/menu.blade.php
@extends('layouts.block', [ "b_options" => ''])

@section('b-title')
    <h2> <i class="fa fa-th"></i> <strong> Overview </strong> </h2>
@overwrite

@section('b-content')
    @parent
    <ul class="nav nav-pills nav-stacked"  data-toggle="tabs">
        <li class="active">
            <a href="#clients">
{{--                <span class="badge pull-right">5</span>--}}
                <i class="fa fa-info-circle fa-fw"></i> <strong>Info</strong>
            </a>
        </li>
    </ul>

@overwrite